#! /bin/bash
hostnames=(ec2-52-0-73-113.compute-1.amazonaws.com
ec2-52-16-219-28.eu-west-1.compute.amazonaws.com
ec2-52-11-8-29.us-west-2.compute.amazonaws.com
ec2-52-8-12-101.us-west-1.compute.amazonaws.com
ec2-52-28-48-84.eu-central-1.compute.amazonaws.com
ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com
ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com
ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com
ec2-54-94-214-108.sa-east-1.compute.amazonaws.com)

while getopts "p:o:u:n:i:" arg
do
    case $arg in
        p) # Port
            ;;
        o) # Origin server
            ;;
        u) # username
            username=$OPTARG
            ;;
        n) # CDN-specific name
            ;;
        i) #private key
            keyfile=$OPTARG
            ;;
        ?)
            echo "unkonw argument"
        exit 1
        ;;
        esac
done

for host in "${hostnames[@]}"
do
    echo "Deploy " $host
    ssh -i $keyfile $username@$host 'mkdir ~/scripts/'
    scp -i $keyfile probeDelay.py $username@$host:~/scripts/
    scp -i $keyfile httpserver $username@$host:~/scripts/
    scp -i $keyfile httpserver.py $username@$host:~/scripts/
done

dnsserver=cs5700cdnproject.ccs.neu.edu
echo "Deploy " $dnsserver
ssh -i $keyfile $username@$dnsserver 'mkdir ~/scripts/'
scp -i $keyfile dnsserver $username@$dnsserver:~/scripts/
scp -i $keyfile dnsserver.py $username@$dnsserver:~/scripts/
scp -i $keyfile getDelay.py $username@$dnsserver:~/scripts/